# Generated by Django 4.2.7 on 2023-12-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='Hiredate',
            field=models.DateField(max_length=100),
        ),
    ]
